name: stdpopsim-rtd

channels:
  - conda-forge

dependencies:
  - _libgcc_mutex==0.1
  - _openmp_mutex==4.5
  - alabaster==0.7.12
  - appdirs==1.4.3
  - attrs==19.3.0
  - babel==2.8.0
  - ca-certificates==2020.4.5.1
  - certifi==2020.4.5.1
  - cffi==1.14.0
  - chardet==3.0.4
  - commonmark==0.7.5
  - cryptography==2.8
  - docutils==0.16
  - future==0.18.2
  - gsl==2.6
  - h5py==2.10.0
  - hdf5==1.10.5
  - humanize==2.2.0
  - idna==2.9
  - imagesize==1.2.0
  - importlib-metadata==1.6.0
  - importlib_metadata==1.6.0
  - jinja2==2.11.1
  - jsonschema==3.2.0
  - ld_impl_linux-64==2.34
  - libblas==3.8.0
  - libcblas==3.8.0
  - libffi==3.2.1
  - libgcc-ng==9.2.0
  - libgfortran-ng==7.3.0
  - liblapack==3.8.0
  - libopenblas==0.3.9
  - libstdcxx-ng==9.2.0
  - llvm-openmp==9.0.1
  - markupsafe==1.1.1
  - msprime==0.7.4
  - ncurses==6.1
  - numpy==1.18.1
  - openssl==1.1.1f
  - packaging==20.1
  - pip==20.0.2
  - pycparser==2.20
  - pygments==2.6.1
  - pyopenssl==19.1.0
  - pyparsing==2.4.7
  - pyrsistent==0.16.0
  - pysocks==1.7.1
  - python==3.8.2
  - python_abi==3.8
  - pytz==2019.3
  - readline==8.0
  - requests==2.23.0
  - setuptools==46.1.3
  - setuptools-scm==3.5.0
  - setuptools_scm==3.5.0
  - six==1.14.0
  - snowballstemmer==2.0.0
  - sphinx==3.0.0
  - sphinx-argparse==0.2.5
  - sphinx-issues==1.2.0
  - sphinxcontrib-applehelp==1.0.2
  - sphinxcontrib-devhelp==1.0.2
  - sphinxcontrib-htmlhelp==1.0.3
  - sphinxcontrib-jsmath==1.0.1
  - sphinxcontrib-programoutput==0.16
  - sphinxcontrib-qthelp==1.0.3
  - sphinxcontrib-serializinghtml==1.1.4
  - sqlite==3.30.1
  - svgwrite==1.4
  - tk==8.6.10
  - tskit==0.2.3
  - urllib3==1.25.7
  - wheel==0.34.2
  - xz==5.2.4
  - zipp==3.1.0
  - zlib==1.2.11
