name: stdpopsim-rtd

channels:
  - conda-forge

dependencies:
  - python==3.6
  - setuptools_scm
  - attrs
  - appdirs
  - msprime
  - sphinx-argparse
  - sphinx-issues
  - sphinxcontrib-programoutput
  - humanize
